# ======================================================================
# GolangCI-Lint Configuration — Egg Framework (2025 Edition)
# ----------------------------------------------------------------------
# Purpose:
#   Ensure consistent, high-quality Go code across all modules
#   Compatible with golangci-lint v1.60+ (2025)
# ======================================================================

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

# ----------------------------------------------------------------------
# Directories and exclusions
# ----------------------------------------------------------------------
issues:
  exclude-dirs:
    - gen                # Skip generated code
    - vendor             # Skip vendored dependencies
    - third_party        # Skip external sources
  exclude-use-default: false
  uniq-by-line: true
  max-same-issues: 0
  new-from-rev: HEAD~1
  show-stats: true

# ----------------------------------------------------------------------
# Linter selection — modern, stable, and low-noise
# ----------------------------------------------------------------------
linters:
  enable:
    # --- Core correctness ---
    - govet              # Standard vet analysis (includes field alignment)
    - staticcheck        # Advanced static analysis
    - gosimple           # Simplify idiomatic Go code
    - errcheck           # Check for unchecked errors
    - typecheck          # Verify type correctness
    - unused             # Detect unused code

    # --- Security & robustness ---
    - gosec              # Security vulnerability detection
    - errorlint          # Proper error wrapping and assertions
    - nilerr             # Detect returning nil errors

    # --- Code style & consistency ---
    - revive             # Modern replacement for golint
    - gofmt              # Enforce formatting
    - goimports          # Enforce import grouping
    - misspell           # Detect spelling errors
    - whitespace         # Check spacing and indentation
    - wsl                # Whitespace/statement layout (no cuddled blocks)

    # --- Code hygiene & maintainability ---
    - unparam            # Detect unused parameters
    - dupl               # Detect code duplication
    - gocritic           # Performance and style improvements
    - prealloc           # Recommend slice preallocation

  disable:
    # Disabled for flexibility in large frameworks
    - funlen             # Function length
    - gochecknoglobals   # Global variables allowed for registry/singletons
    - gochecknoinits     # init() usage allowed for bootstrap
    - cyclop             # Cyclomatic complexity
    - exhaustive         # Exhaustive switch enforcement
    - godot              # Periods in comments (style preference)

# ----------------------------------------------------------------------
# Per-linter configuration
# ----------------------------------------------------------------------
linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment    # Avoid duplicate reporting (already implicit)

  errcheck:
    check-type-assertions: true
    check-blank: true

  goimports:
    local-prefixes: github.com/eggybyte-technology/egg

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: unused-parameter
      - name: indent-error-flow
      - name: if-return
      - name: early-return
      - name: context-as-argument
      - name: receiver-naming
      - name: error-naming
      - name: var-naming
      - name: package-comments
      - name: import-shadowing

  wsl:
    allow-cuddle-declarations: false
    allow-multiline-assign: false
    allow-assign-and-call: false
    force-case-trailing-whitespace: true

  gosec:
    excludes:
      - G104              # Allow explicitly ignored errors
      - G601              # Allow pointer copying in controlled contexts

  gocritic:
    enabled-checks:
      - ruleguard
      - truncateCmp
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

# ----------------------------------------------------------------------
# Output configuration (modern format)
# ----------------------------------------------------------------------
output:
  formats:
    - format: colored-line-number
  sort-results: true

# ----------------------------------------------------------------------
# End of configuration
# ======================================================================
# Usage:
#   golangci-lint run ./...
#   goimports -w . && gofmt -s -w .
# ======================================================================
