services:
  user-service:
    build:
      context: ../backend/user-service
      dockerfile: ../../build/Dockerfile.backend
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9091:9091"
    environment:
      - LOG_LEVEL=info
      - KUBERNETES_NAMESPACE=prod
      - DATABASE_DSN=user:pass@tcp(mysql:3306)/app?charset=utf8mb4&parseTime=True
      - SERVICE_NAME=user-service
      - RATE_LIMIT_QPS=value-from-global-config-FEATURE_A
      - HTTP_PORT=8080
      - HEALTH_PORT=8081
      - METRICS_PORT=9091
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: test-cli-project-network
