# Egg Framework Docker Compose Configuration
# This file defines the services and their port allocations
#
# Port Allocation:
#   MySQL:           3306
#   Jaeger UI:       16686
#   Jaeger Collector: 14268
#   OTLP gRPC:       4317
#   OTLP HTTP:       4318
#   Prometheus:      8889
#
#   Minimal Service:
#     - HTTP:        8080 (container) -> 8080 (host)
#     - Health:      8081 (container) -> 8081 (host)
#     - Metrics:     9091 (container) -> 9091 (host)
#
#   User Service:
#     - HTTP:        8080 (container) -> 8082 (host)
#     - Health:      8081 (container) -> 8083 (host)
#     - Metrics:     9091 (container) -> 9092 (host)
#
# Environment Variables:
#   Services expect port numbers without colons (e.g., "8080", not ":8080")
#   servicex automatically adds the colon prefix internally (":8080")
#   This matches the configx.BaseConfig expectations.

services:
  # MySQL Database
  mysql:
    image: mysql:9.4
    container_name: egg-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: egg_users
      MYSQL_USER: egg_user
      MYSQL_PASSWORD: egg_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - egg-network

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: egg-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics
    depends_on:
      - jaeger
    networks:
      - egg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8889/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: egg-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - egg-network

  # Minimal Connect Service
  minimal-service:
    image: minimal-connect-service:latest
    container_name: egg-minimal-service
    environment:
      SERVICE_NAME: minimal-connect-service
      SERVICE_VERSION: 1.0.0
      ENV: development
      HTTP_PORT: 8080
      HEALTH_PORT: 8081
      METRICS_PORT: 9091
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      APP_CONFIGMAP_NAME: ""  # Empty means use environment variables only
      CONFIG_DEBOUNCE_MS: 200
      SLOW_REQUEST_MILLIS: 1000
      RATE_LIMIT_QPS: 100
      ENABLE_DEBUG_LOGS: "true"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9091:9091"
    depends_on:
      - otel-collector
    networks:
      - egg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # User Service
  user-service:
    image: user-service:latest
    container_name: egg-user-service
    environment:
      SERVICE_NAME: user-service
      SERVICE_VERSION: 1.0.0
      ENV: development
      HTTP_PORT: 8080
      HEALTH_PORT: 8081
      METRICS_PORT: 9091
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      APP_CONFIGMAP_NAME: ""  # Empty means use environment variables only
      CONFIG_DEBOUNCE_MS: 200
      DB_DRIVER: mysql
      DB_DSN: egg_user:egg_password@tcp(mysql:3306)/egg_users?charset=utf8mb4&parseTime=True&loc=Local
      DB_MAX_IDLE: "10"
      DB_MAX_OPEN: "100"
      DB_MAX_LIFETIME: 1h
      DEFAULT_PAGE_SIZE: 10
      MAX_PAGE_SIZE: 100
      SLOW_QUERY_MILLIS: 1000
      ENABLE_DEBUG_LOGS: "true"
      ENABLE_METRICS: "true"
      ENABLE_TRACING: "true"
      ENABLE_HEALTH_CHECK: "true"
    ports:
      - "8082:8080"
      - "8083:8081"
      - "9092:9091"
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - egg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mysql_data:

networks:
  egg-network:
    driver: bridge
