# OpenTelemetry Collector Configuration for Egg Framework
#
# This configuration receives telemetry data via OTLP protocol and exports to:
#   - Console (debug logging)
#   - Prometheus (metrics on port 8889)
#   - Jaeger (traces via OTLP on port 4317)
#
# Note: We use otlp/jaeger exporter instead of the deprecated jaeger exporter

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
