// Code generated by cli-release.sh. DO NOT EDIT.
package generators

// FrameworkVersion is the Egg framework version that this CLI release uses.
// This version is used when generating new projects.
// For development builds, this will be empty and getFrameworkVersion() will return "latest".
const FrameworkVersion = ""

