// Code generated by cli-release.sh. DO NOT EDIT.
package generators

// FrameworkVersion is the Egg framework version that this CLI release uses.
// This version is used when generating new projects.
const FrameworkVersion = "v0.3.2"
